/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.finansoft.visualizar;

import br.com.finansoft.controle.FormataMoeda;
import javax.swing.JOptionPane;

/**
 *
 * @author jereelton
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoDescricaoDespesaJLabel = new javax.swing.JLabel();
        textoValorDespesaJLabel = new javax.swing.JLabel();
        textoDataDespesaJLabel = new javax.swing.JLabel();
        textoFinansoftJLabel = new javax.swing.JLabel();
        textoControleFinanceiroPessoalJLabel = new javax.swing.JLabel();
        textoMoedaJLabel = new javax.swing.JLabel();
        logoSistemaJLabel = new javax.swing.JLabel();
        outrasDespesasJTextField = new javax.swing.JTextField();
        dataDespesaJTextField = new javax.swing.JTextField();
        descricaoDespesaJComboBox = new javax.swing.JComboBox();
        outrasDespesasJCheckBox = new javax.swing.JCheckBox();
        adicionarDespesaJButton = new javax.swing.JButton();
        salvarDespesaJButton = new javax.swing.JButton();
        salvarDespesasJButton = new javax.swing.JButton();
        valorDespesaJTextField = new javax.swing.JTextField();
        menuSistemaJMenuBar = new javax.swing.JMenuBar();
        menuSistemaJMenu = new javax.swing.JMenu();
        ItemMenuSairJMenuItem = new javax.swing.JMenuItem();
        menuFerramentasJMenu = new javax.swing.JMenu();
        itemMenuRelatoriosJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Financeiro");
        setMinimumSize(new java.awt.Dimension(600, 360));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 375));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 375));

        textoDescricaoDespesaJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoDescricaoDespesaJLabel.setText("Descrição Despesa");

        textoValorDespesaJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoValorDespesaJLabel.setText("Valor Despesa");

        textoDataDespesaJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoDataDespesaJLabel.setText("Data Despesa");

        textoFinansoftJLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textoFinansoftJLabel.setForeground(new java.awt.Color(0, 102, 204));
        textoFinansoftJLabel.setText("FINANSOFT");

        textoControleFinanceiroPessoalJLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textoControleFinanceiroPessoalJLabel.setText("Controle Financeiro Pessoal");

        textoMoedaJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoMoedaJLabel.setText("R$");

        logoSistemaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizar/imagens/icone_controle_financeiro.png"))); // NOI18N

        outrasDespesasJTextField.setEnabled(false);
        outrasDespesasJTextField.setMaximumSize(new java.awt.Dimension(190, 24));
        outrasDespesasJTextField.setMinimumSize(new java.awt.Dimension(190, 24));
        outrasDespesasJTextField.setPreferredSize(new java.awt.Dimension(190, 24));

        dataDespesaJTextField.setMaximumSize(new java.awt.Dimension(130, 24));
        dataDespesaJTextField.setMinimumSize(new java.awt.Dimension(130, 24));
        dataDespesaJTextField.setPreferredSize(new java.awt.Dimension(130, 24));

        descricaoDespesaJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma despesa...", "Gasolina", "Supermercado", "Farmacia", "Conta de Luz", "Conta de Agua", "Condominio", " " }));
        descricaoDespesaJComboBox.setMaximumSize(new java.awt.Dimension(190, 24));
        descricaoDespesaJComboBox.setMinimumSize(new java.awt.Dimension(190, 24));
        descricaoDespesaJComboBox.setPreferredSize(new java.awt.Dimension(190, 24));
        descricaoDespesaJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoDespesaJComboBoxActionPerformed(evt);
            }
        });

        outrasDespesasJCheckBox.setText("Outras Despesas");
        outrasDespesasJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrasDespesasJCheckBoxActionPerformed(evt);
            }
        });

        adicionarDespesaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizar/imagens/icone_adicionar.png"))); // NOI18N
        adicionarDespesaJButton.setToolTipText("Adicionar Despesa");
        adicionarDespesaJButton.setMaximumSize(new java.awt.Dimension(80, 80));
        adicionarDespesaJButton.setMinimumSize(new java.awt.Dimension(80, 80));
        adicionarDespesaJButton.setPreferredSize(new java.awt.Dimension(80, 80));

        salvarDespesaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizar/imagens/icone_limpar.png"))); // NOI18N
        salvarDespesaJButton.setToolTipText("Limpar Campos");
        salvarDespesaJButton.setMaximumSize(new java.awt.Dimension(80, 80));
        salvarDespesaJButton.setMinimumSize(new java.awt.Dimension(80, 80));
        salvarDespesaJButton.setPreferredSize(new java.awt.Dimension(80, 80));
        salvarDespesaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarDespesaJButtonActionPerformed(evt);
            }
        });

        salvarDespesasJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizar/imagens/icone_salvar.png"))); // NOI18N
        salvarDespesasJButton.setToolTipText("Salvar Despesas");
        salvarDespesasJButton.setMaximumSize(new java.awt.Dimension(80, 80));
        salvarDespesasJButton.setMinimumSize(new java.awt.Dimension(80, 80));
        salvarDespesasJButton.setPreferredSize(new java.awt.Dimension(80, 80));

        valorDespesaJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorDespesaJTextField.setMaximumSize(new java.awt.Dimension(130, 24));
        valorDespesaJTextField.setMinimumSize(new java.awt.Dimension(130, 24));
        valorDespesaJTextField.setPreferredSize(new java.awt.Dimension(130, 24));
        valorDespesaJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorDespesaJTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(logoSistemaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoFinansoftJLabel)
                            .addComponent(textoControleFinanceiroPessoalJLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outrasDespesasJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoDescricaoDespesaJLabel)
                                    .addComponent(descricaoDespesaJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outrasDespesasJCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoMoedaJLabel)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(adicionarDespesaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoValorDespesaJLabel)
                            .addComponent(salvarDespesaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorDespesaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salvarDespesasJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDataDespesaJLabel)
                            .addComponent(dataDespesaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoSistemaJLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(textoFinansoftJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoControleFinanceiroPessoalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDescricaoDespesaJLabel)
                    .addComponent(textoValorDespesaJLabel)
                    .addComponent(textoDataDespesaJLabel))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoDespesaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDespesaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMoedaJLabel)
                    .addComponent(valorDespesaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outrasDespesasJCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outrasDespesasJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(salvarDespesaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionarDespesaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salvarDespesasJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        menuSistemaJMenuBar.setMaximumSize(new java.awt.Dimension(600, 25));
        menuSistemaJMenuBar.setMinimumSize(new java.awt.Dimension(600, 25));
        menuSistemaJMenuBar.setPreferredSize(new java.awt.Dimension(600, 25));

        menuSistemaJMenu.setText("Sistema");
        menuSistemaJMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuSistemaJMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuSistemaJMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuSistemaJMenu.setMaximumSize(new java.awt.Dimension(100, 25));
        menuSistemaJMenu.setMinimumSize(new java.awt.Dimension(100, 25));
        menuSistemaJMenu.setPreferredSize(new java.awt.Dimension(100, 25));

        ItemMenuSairJMenuItem.setText("Sair");
        ItemMenuSairJMenuItem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ItemMenuSairJMenuItem.setMaximumSize(new java.awt.Dimension(200, 25));
        ItemMenuSairJMenuItem.setMinimumSize(new java.awt.Dimension(200, 25));
        ItemMenuSairJMenuItem.setPreferredSize(new java.awt.Dimension(200, 25));
        ItemMenuSairJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuSairJMenuItemActionPerformed(evt);
            }
        });
        menuSistemaJMenu.add(ItemMenuSairJMenuItem);

        menuSistemaJMenuBar.add(menuSistemaJMenu);

        menuFerramentasJMenu.setText("Ferramentas");
        menuFerramentasJMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFerramentasJMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuFerramentasJMenu.setMaximumSize(new java.awt.Dimension(100, 25));
        menuFerramentasJMenu.setMinimumSize(new java.awt.Dimension(100, 25));
        menuFerramentasJMenu.setPreferredSize(new java.awt.Dimension(100, 25));

        itemMenuRelatoriosJMenuItem.setText("Relatórios");
        itemMenuRelatoriosJMenuItem.setMaximumSize(new java.awt.Dimension(200, 25));
        itemMenuRelatoriosJMenuItem.setMinimumSize(new java.awt.Dimension(200, 25));
        itemMenuRelatoriosJMenuItem.setPreferredSize(new java.awt.Dimension(200, 25));
        itemMenuRelatoriosJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatoriosJMenuItemActionPerformed(evt);
            }
        });
        menuFerramentasJMenu.add(itemMenuRelatoriosJMenuItem);

        menuSistemaJMenuBar.add(menuFerramentasJMenu);

        setJMenuBar(menuSistemaJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(610, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoDespesaJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoDespesaJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoDespesaJComboBoxActionPerformed

    private void outrasDespesasJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrasDespesasJCheckBoxActionPerformed

        if(outrasDespesasJCheckBox.isSelected()) {
        
            outrasDespesasJTextField.setEnabled(true);
            descricaoDespesaJComboBox.setSelectedIndex(0);
            descricaoDespesaJComboBox.setEnabled(false);
        
        } else {
        
            outrasDespesasJTextField.setEnabled(false);
            descricaoDespesaJComboBox.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_outrasDespesasJCheckBoxActionPerformed

    private void salvarDespesaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarDespesaJButtonActionPerformed
        
        descricaoDespesaJComboBox.setSelectedIndex(0);
        outrasDespesasJCheckBox.setSelected(false);
        outrasDespesasJTextField.setText("");
        outrasDespesasJTextField.setEnabled(false);
        valorDespesaJTextField.setText("");
        dataDespesaJTextField.setText("");
        
    }//GEN-LAST:event_salvarDespesaJButtonActionPerformed

    private void ItemMenuSairJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuSairJMenuItemActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_ItemMenuSairJMenuItemActionPerformed

    private void itemMenuRelatoriosJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatoriosJMenuItemActionPerformed
        
        JOptionPane.showMessageDialog(this, "Função Relatórios");
        
    }//GEN-LAST:event_itemMenuRelatoriosJMenuItemActionPerformed

    private void valorDespesaJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDespesaJTextFieldKeyReleased
        
        FormataMoeda formatoMoeda = new FormataMoeda(valorDespesaJTextField.getText());
        
        valorDespesaJTextField.setText(formatoMoeda.formatar());
        
    }//GEN-LAST:event_valorDespesaJTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuSairJMenuItem;
    private javax.swing.JButton adicionarDespesaJButton;
    private javax.swing.JTextField dataDespesaJTextField;
    private javax.swing.JComboBox descricaoDespesaJComboBox;
    private javax.swing.JMenuItem itemMenuRelatoriosJMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoSistemaJLabel;
    private javax.swing.JMenu menuFerramentasJMenu;
    private javax.swing.JMenu menuSistemaJMenu;
    private javax.swing.JMenuBar menuSistemaJMenuBar;
    private javax.swing.JCheckBox outrasDespesasJCheckBox;
    private javax.swing.JTextField outrasDespesasJTextField;
    private javax.swing.JButton salvarDespesaJButton;
    private javax.swing.JButton salvarDespesasJButton;
    private javax.swing.JLabel textoControleFinanceiroPessoalJLabel;
    private javax.swing.JLabel textoDataDespesaJLabel;
    private javax.swing.JLabel textoDescricaoDespesaJLabel;
    private javax.swing.JLabel textoFinansoftJLabel;
    private javax.swing.JLabel textoMoedaJLabel;
    private javax.swing.JLabel textoValorDespesaJLabel;
    private javax.swing.JTextField valorDespesaJTextField;
    // End of variables declaration//GEN-END:variables
}
